name: .NET CI/CD

# Trigger workflow on push or PR to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  HEROKU_WEBAPP_NAME: sample-ci-cd-example
  HEROKU_WEBAPP_PACKAGE_PATH: "./publish"
  DOTNET_VERSION: '8.0.x'
  API_PROJECT_PATH: 'SampleCICD_Example' # Replace with your actual API project name
  PUBLISH_DIR: 'publish'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - uses: actions/checkout@v4

      # Step 2: Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run unit tests
      - name: Run tests
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build -o ${{ env.PUBLISH_DIR }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'webapp'
          path: ${{ env.HEROKU_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build-and-test]
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: 'webapp'
          path: ${{ env.HEROKU_WEBAPP_PACKAGE_PATH }}

      - name: Install Heroku CLI
          run:
            curl https://cli-assets.heroku.com/install.sh | sh
  
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "sample-ci-cd-example" # Replace with your app name
          heroku_email: "Khusrav837@gmail.com"   # Replace with your Heroku email

